image_ext = [
    'bmp',
    'gif',
    'ico',
    'jpeg',
    'jpg',
    'png',
    'tif',
    'tiff',
]

undef_ext = [
]

file_type = {
    'aif': 'audio',
    'cda': 'audio',
    'mid': 'audio',
    'mp3': 'audio',
    'mpa': 'audio',
    'ogg': 'audio',
    'wav': 'audio',
    'wma': 'audio',
    'wpl': 'audio',

    '7z': 'zip',  
    'arj': 'zip', 
    'deb': 'zip', 
    'pkg': 'package', 
    'rar': 'zip', 
    'rpm': 'zip', 
    'gz': 'zip',  
    'z': 'zip',   
    'zip': 'zip', 

    'csv': 'csv',
    'dat': 'data',
    'db': 'database',
    'db3': 'database',
    'log': 'text',
    'mdb': 'database',
    'sav': 'data',
    'sql': 'database',
    'sqlite': 'database',
    'tar': 'package',
    'xml': 'xml',
    'yml': 'yml',
    'json': 'json',

    'email': 'mail', 
    'eml': 'mail',  
    'emlx': 'mail', 
    'msg': 'outlook',
    'oft': 'outlook',
    'ost': 'outlook',
    'pst': 'mail',
    'vcf': 'mail',

    'apk': 'package',
    'bat': 'exe',
    'bin': 'exe',
    'cgi': 'perl',
    'pl': 'perl', 
    'pm': 'pm',
    'rb': 'ruby',
    'com': 'exe',
    'exe': 'exe',
    'gadget': 'misc',
    'jar': 'java', 
    'msi': 'install', 
    'py': 'python', 
    'wsf': 'exe', 

    'fnt': 'font',
    'fon': 'font',
    'otf': 'font',
    'ttf': 'font',

    'ai': 'image',
    'bmp': 'image',
    'gif': 'image',
    'ico': 'image',
    'jpeg': 'image',
    'jpg': 'image',
    'png': 'image',
    'ps': 'image',
    'psd': 'image',
    'svg': 'image',
    'tif': 'image',
    'tiff': 'image',

    'asp': 'web',
    'aspx': 'web',
    'cer': 'certificate',
    'cfm': 'web',
    'css': 'css',
    'htm': 'html',
    'html': 'html',
    'js': 'javascript',
    'jsp': 'web',
    'part': 'web',
    'php': 'web',
    'rss': 'rss',
    'xhtml': 'web',

    'key': 'presentation',
    'odp': 'presentation',
    'pps': 'powerpoint',
    'ppt': 'powerpoint',
    'pptx': 'powerpoint',

    'c': 'c',
    'class': 'java',
    'cpp': 'c',
    'cs': 'c',
    'h': 'c',
    'java': 'java',
    'php': 'text',
    'sh': 'exe',
    'swift': 'text',
    'vba': 'vba',
    'vb': 'vb',

    'ods': 'spreadsheet',
    'xls': 'excel',
    'xlsm': 'excel',
    'xlsx': 'excel',
    'xla': 'xla',

    'bak': 'bak',
    'cab': 'misc',
    'cfg': 'config',
    'cpl': 'config',
    'cur': 'misc',
    'dll': 'lib',
    'dmp': 'data',
    'icns': 'image',
    'ico': 'image',
    'ini': 'config',
    'lnk': 'link',
    'msi': 'install',
    'sys': 'prompt',
    'tmp': 'misc',

    '3g2': 'video',
    '3gp': 'video',
    'avi': 'video',
    'flv': 'video',
    'h264': 'video',
    'm4v': 'video',
    'mkv': 'video',
    'mov': 'video',
    'mp4': 'video',
    'mpg': 'video',
    'rm': 'video',
    'swf': 'video',
    'vob': 'video',
    'wmv': 'video',

    'doc': 'word',
    'docx': 'word',
    'odt': 'document',
    'pdf': 'pdf',
    'rtf': 'misc',
    'txt': 'text',
    'wpd': 'document',
}
