# Generated by Django 3.1.3 on 2021-08-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='A slug is unique name reference for the page.  Once created, do not change the slug -- not unless all page references that use it are also changed.', max_length=200, unique=True, verbose_name='Slug')),
                ('intro', models.TextField(help_text="First few sentences of the content, before the 'Read More' link.", verbose_name='Intro')),
                ('content', models.TextField(help_text='Remainder of the article content.', verbose_name='Content')),
                ('priority', models.IntegerField(default=50, help_text='Priority order (where 1 is the highest priority).', verbose_name='Priority')),
                ('featured', models.BooleanField(default=False, help_text='Add to front page?', verbose_name='Enable Team Access')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
