# Generated by Django 3.1.3 on 2021-08-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, help_text='Make a featured article?', verbose_name='Featured'),
        ),
    ]
