# Generated by Django 3.1.3 on 2021-08-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210816_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='intro',
        ),
    ]
