# Generated by Django 3.1.3 on 2021-08-07 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210806_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='start_hole',
            field=models.IntegerField(blank=True, help_text='Hole that the team starts on.', null=True, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)], verbose_name='Start Hole'),
        ),
    ]
