# Generated by Django 3.1.3 on 2021-08-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_team_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('par', models.IntegerField(blank=True, null=True, verbose_name='Par')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Rating')),
                ('slope', models.FloatField(blank=True, null=True, verbose_name='Slope')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='CourseHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.IntegerField(blank=True, null=True, verbose_name='Hole')),
                ('par', models.IntegerField(blank=True, null=True, verbose_name='Par')),
                ('handicap', models.IntegerField(blank=True, null=True, verbose_name='Handicap')),
                ('blue', models.IntegerField(blank=True, null=True, verbose_name='Blue')),
                ('white', models.IntegerField(blank=True, null=True, verbose_name='White')),
                ('red', models.IntegerField(blank=True, null=True, verbose_name='White')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
