# Generated by Django 3.1.3 on 2021-08-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210806_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseHole',
            new_name='Hole',
        ),
    ]
