# Generated by Django 3.1.3 on 2021-08-07 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210806_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='hole',
            name='gold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gold'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Name')),
                ('date_time', models.DateTimeField(blank=True, help_text='Tournament date and start time.', null=True, verbose_name='Updated On')),
                ('play_from', models.CharField(choices=[('gold', 'Gold tees'), ('blue', 'Blue tees'), ('white', 'White tees'), ('red', 'Red tees')], default='white', max_length=100, verbose_name='Play From')),
                ('enable_team_access', models.BooleanField(default=False, verbose_name='Enable Team Access')),
                ('enable_team_input', models.BooleanField(default=False, verbose_name='Enable Team Input')),
                ('show_leader_board', models.BooleanField(default=False, verbose_name='Show Leader Board')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
