# Generated by Django 3.1.3 on 2021-08-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210806_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
