# Generated by Django 3.1.3 on 2021-08-07 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tournament_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hole9',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 9 Score'),
        ),
    ]
