# Generated by Django 3.1.3 on 2021-08-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_team_hole9'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='holes_played',
            field=models.IntegerField(blank=True, null=True, verbose_name='Holes Played'),
        ),
    ]
