# Generated by Django 3.1.3 on 2021-08-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_team_holes_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='red',
            field=models.IntegerField(blank=True, null=True, verbose_name='Red'),
        ),
        migrations.CreateModel(
            name='TeamAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
