# Generated by Django 3.1.3 on 2021-08-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210809_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Data')),
            ],
        ),
        migrations.AlterModelOptions(
            name='hole',
            options={'verbose_name_plural': 'Course Info (Holes)'},
        ),
        migrations.AlterModelOptions(
            name='teamaccess',
            options={'verbose_name_plural': 'Team Access'},
        ),
    ]
