# Generated by Django 3.1.3 on 2021-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210810_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='epoch',
            field=models.IntegerField(default=0, verbose_name='Epoch Timestamp'),
        ),
    ]
