# Generated by Django 3.1.3 on 2021-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cache_epoch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cache',
            options={'verbose_name': 'Compiled Data Cache', 'verbose_name_plural': 'Compiled Data Cache'},
        ),
        migrations.AlterModelOptions(
            name='hole',
            options={'verbose_name': 'Course Info (Holes)', 'verbose_name_plural': 'Course Info (Holes)'},
        ),
        migrations.AlterModelOptions(
            name='teamaccess',
            options={'verbose_name': 'Team Access', 'verbose_name_plural': 'Team Access Records'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_results',
            field=models.BooleanField(default=False, verbose_name='Show Results'),
        ),
    ]
