# Generated by Django 3.1.3 on 2021-08-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210810_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='proj_adj_raw_score',
        ),
    ]
