# Generated by Django 3.1.3 on 2021-08-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_team_proj_adj_raw_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='special',
            field=models.CharField(choices=[('closest to the hole', 'Closest to the hole'), ('longest drive', 'Longest drive')], default='white', max_length=100, verbose_name='Play From'),
        ),
    ]
