# Generated by Django 3.1.3 on 2021-08-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_hole_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='special',
            field=models.CharField(blank=True, choices=[('closest to the hole', 'Closest to the hole'), ('longest drive', 'Longest drive')], max_length=100, null=True, verbose_name='Play From'),
        ),
    ]
