# Generated by Django 3.1.3 on 2021-08-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210811_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score_calculated',
            field=models.BooleanField(default=False, verbose_name='Score Calculated'),
        ),
    ]
