# Generated by Django 3.1.3 on 2021-08-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_team_score_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='special',
            field=models.CharField(blank=True, choices=[('Closest to the Hole', 'Closest to the Hole'), ('Longest Drive', 'Longest Drive')], max_length=100, null=True, verbose_name='Special'),
        ),
    ]
