# Generated by Django 3.1.3 on 2021-08-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210813_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100, verbose_name='Token')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('is_best', models.BooleanField(default=True, verbose_name='Currently the Closest or Longest?')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'verbose_name': 'Closest to the Hole / Longest Drive Award',
                'verbose_name_plural': 'Closest to the Hole / Longest Drive Awards',
            },
        ),
    ]
