# Generated by Django 3.1.3 on 2021-08-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_type',
            field=models.CharField(default='Closest to the Hole', max_length=100, verbose_name='Award Type'),
        ),
        migrations.AlterField(
            model_name='award',
            name='is_best',
            field=models.BooleanField(default=True, verbose_name='Current Best?'),
        ),
        migrations.AlterField(
            model_name='award',
            name='player',
            field=models.CharField(max_length=100, verbose_name='Player'),
        ),
    ]
