# Generated by Django 3.1.3 on 2021-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210814_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='final_adj_raw_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Raw Score'),
        ),
        migrations.AlterField(
            model_name='team',
            name='final_adj_rel_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Relative Score'),
        ),
    ]
