# Generated by Django 3.1.3 on 2021-08-23 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210821_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('player1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 1')),
                ('player2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 2')),
                ('player3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 3')),
                ('handicap', models.IntegerField(blank=True, null=True, verbose_name='Handicap')),
                ('start_hole', models.IntegerField(blank=True, help_text='Hole that the team starts on.', null=True, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)], verbose_name='Start Hole')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Password')),
                ('hole1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 1 Score')),
                ('hole2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 2 Score')),
                ('hole3', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 3 Score')),
                ('hole4', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 4 Score')),
                ('hole5', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 5 Score')),
                ('hole6', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 6 Score')),
                ('hole7', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 7 Score')),
                ('hole8', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 8 Score')),
                ('hole9', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 9 Score')),
                ('hole10', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 10 Score')),
                ('hole11', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 11 Score')),
                ('hole12', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 12 Score')),
                ('hole13', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 13 Score')),
                ('hole14', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 14 Score')),
                ('hole15', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 15 Score')),
                ('hole16', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 16 Score')),
                ('hole17', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 17 Score')),
                ('hole18', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Hole 18 Score')),
                ('holes_played', models.IntegerField(blank=True, null=True, verbose_name='Holes Played')),
                ('current_raw_score', models.IntegerField(blank=True, null=True, verbose_name='Current Raw Score')),
                ('current_rel_score', models.IntegerField(blank=True, null=True, verbose_name='Current Relative Score')),
                ('final_adj_raw_score', models.IntegerField(blank=True, null=True, verbose_name='Final Adjusted Raw Score')),
                ('final_adj_rel_score', models.IntegerField(blank=True, null=True, verbose_name='Final Adjusted Relative Score')),
                ('proj_adj_rel_score', models.IntegerField(blank=True, null=True, verbose_name='Projected Adjusted Relative Score')),
                ('updated_on', models.DateTimeField(blank=True, help_text='Scored last updated on.', null=True, verbose_name='Updated On')),
                ('sortable_score', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sortable Score')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment')),
                ('score_calculated', models.BooleanField(default=False, verbose_name='Score Calculated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournament')),
            ],
        ),
    ]
