# Generated by Django 3.1.3 on 2021-08-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210822_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Past Tournament Results', 'verbose_name_plural': 'Past Tournament Results'},
        ),
    ]
