# Generated by Django 3.1.3 on 2021-08-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210822_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='archive_notes',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Notes'),
        ),
    ]
