# Generated by Django 3.1.3 on 2021-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_tournament_archive_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='holes_played',
            field=models.IntegerField(default=0, verbose_name='Holes Played'),
        ),
    ]
