# Generated by Django 3.1.3 on 2021-08-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210823_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='current_raw_score',
            field=models.IntegerField(default=0, verbose_name='Current Raw Score'),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_rel_score',
            field=models.IntegerField(default=0, verbose_name='Current Relative Score'),
        ),
        migrations.AlterField(
            model_name='team',
            name='final_adj_raw_score',
            field=models.IntegerField(default=0, verbose_name='Final Adjusted Raw Score'),
        ),
        migrations.AlterField(
            model_name='team',
            name='final_adj_rel_score',
            field=models.IntegerField(default=0, verbose_name='Final Adjusted Relative Score'),
        ),
        migrations.AlterField(
            model_name='team',
            name='proj_adj_rel_score',
            field=models.IntegerField(default=0, verbose_name='Projected Adjusted Relative Score'),
        ),
    ]
