# Generated by Django 3.1.3 on 2021-08-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210823_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('spelling', models.CharField(help_text='If I have mis-spelled your name, please help me get it right the next time.', max_length=100, verbose_name='Name (Spelled Correctly)')),
                ('email', models.CharField(blank=True, help_text='Please provide at least one of your email address or text capable cell phone number.', max_length=200, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Please provide at least one of your email address or text capable cell phone number.', max_length=100, null=True, verbose_name='Cell Number')),
                ('handicap', models.FloatField(blank=True, help_text='Do you know your handicap?  If so, please provide.', null=True, verbose_name='Handicap')),
                ('score', models.IntegerField(blank=True, help_text="If you don't know your handicap, can you provide an average score?", null=True, verbose_name='Average Score')),
                ('vote', models.CharField(blank=True, choices=[('koozies', 'Koozies are good enough for me!'), ('trophies', 'Honestly, I liked tophies better.'), ('koozies and trophies', 'I vote for koozies and (smaller) trophies')], help_text='This year we are doing koozies in lieu of trophies.  But next year I will do whatever the consensus wants.  Just know that if we go back to trophies, it probably means we have to raise entry fees.', max_length=100, null=True, verbose_name='Your Vote: Trophies or Koozies?')),
                ('comment', models.CharField(blank=True, help_text='Comments? Questions? Complaints?  If you want to kindly suggest any changes to our tournament, this is your chance.', max_length=10000, null=True, verbose_name='Comment')),
            ],
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Hole Award', 'verbose_name_plural': 'Hole Awards'},
        ),
        migrations.AlterModelOptions(
            name='hole',
            options={'verbose_name': 'Course Hole Info', 'verbose_name_plural': 'Course Holes Info'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'All Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamaccess',
            options={'verbose_name': 'Team Access Token', 'verbose_name_plural': 'Team Access Tokens'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Tournament', 'verbose_name_plural': 'All Tournaments'},
        ),
        migrations.AlterField(
            model_name='history',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Comment'),
        ),
    ]
