# Generated by Django 3.1.3 on 2021-08-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210826_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='spelling',
            field=models.CharField(blank=True, help_text='If I have mis-spelled your name, please help me get it right the next time.', max_length=100, null=True, verbose_name='Name (Spelled Correctly)'),
        ),
    ]
