# Generated by Django 3.1.3 on 2021-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210826_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='comment',
            field=models.CharField(blank=True, help_text='Comments? Questions? Complaints?  If you want to kindly suggest any changes to our tournament, this is your chance.', max_length=10000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='player',
            name='spelling',
            field=models.CharField(blank=True, help_text='If I have mis-spelled your name, please help me get it right the next time.', max_length=100, null=True, verbose_name='Your Name (if not spelled correctly above)'),
        ),
    ]
