# Generated by Django 3.1.3 on 2022-06-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_team_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history',
            field=models.IntegerField(default=0, help_text='First tiebreaker is tournament history. Number > 0 means team includes players that have recently have had 1st, 2nd, or 3rd place finish.', verbose_name='History'),
        ),
    ]
