# Generated by Django 3.1.3 on 2022-06-14 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_history_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='main.course'),
        ),
    ]
